<a href="https://colab.research.google.com/github/Vrinda-2004/Assessmenttest/blob/main/NUMPY%26PANDASACTIVITIES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY ACTIVITY

In [1]:
import numpy as np

In [2]:
array=np.arange(10, 50)
x=array.reshape(4,10)# reshaped into 4 rows and 10 columns
y=x[:,-1]# taking last column from reshaped matrix
y

array([19, 29, 39, 49])

In [3]:
matrix_a = np.full((3, 3), 5) # all elements are 5 , 3 by 3 matrix
matrix_b = np.arange(1, 10).reshape(3, 3) # elements range from 1 to 10, and reshaped into 3 by 3 matrix
matrix_sum = matrix_a + matrix_b # adding the both matrix a and b
matrix_multiply = matrix_a * matrix_b # multiplying both matrices
matrix_transpose = matrix_multiply.T # taking the transpose of the matrix multiplication
matrix_transpose # displaying the transpose matrix

array([[ 5, 20, 35],
       [10, 25, 40],
       [15, 30, 45]])

In [4]:
arr = np.random.randint(10,101,15)
x = np.where(arr > 50, -1,arr)
count = (arr>50).sum()
count

np.int64(8)

In [5]:
arr = np.random.rand(5, 4)
row_sums = arr.sum(axis=1) ## Find sum of each row
max_row_index = np.argmax(row_sums)
normalized_arr = arr/ arr.sum(axis=1, keepdims=True)
normalized_arr

array([[0.09641801, 0.05057653, 0.53770043, 0.31530502],
       [0.17431759, 0.21694603, 0.40091308, 0.2078233 ],
       [0.31287464, 0.31863211, 0.29061717, 0.07787608],
       [0.34547576, 0.45340373, 0.18686022, 0.01426028],
       [0.29687751, 0.52099698, 0.12321461, 0.0589109 ]])

In [11]:
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
unique_elements, counts = np.unique(arr, return_counts=True)
unique_elements
duplicates = unique_elements[counts > 1]
duplicates

array([1, 3, 5])

In [12]:
arr = np.arange(1,37).reshape(6,6)
submatrix = arr[1:5, 1:5]
even = submatrix[submatrix % 2 == 0]
even

array([ 8, 10, 14, 16, 20, 22, 26, 28])

In [13]:
arr = np.arange(12).reshape(3, 4)
reshaped_array = arr.reshape(2, 6)
flat_array = reshaped_array.flatten()
final_array = flat_array.reshape(4, 3)
final_array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
a = np.array([[1, 2],
              [3, 4]])
a = np.append(a,[[5,6]], axis = 0)
a = np.append(a,[[7],[8],[9]],axis = 1)
a

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
single_arr = np.concatenate((a,b,c))
reshape = single_arr.reshape(3,3)
diagonal = np.diag(reshape)
diagonal

array([1, 5, 9])

In [18]:
arr = np.arange(1,21)
x = arr[(arr % 3 == 0) | (arr % 5 == 0)]
count = len(x)
count

9

PANDAS ACTIVITY

In [19]:
import pandas as pd
import numpy as np

In [20]:
data = pd.read_csv("/content/titanic_dataset.csv")
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [22]:
data.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C


In [23]:
data.isnull().sum()

,0
PassengerId,0
Survived,0
Pclass,0
Name,0
Sex,0
Age,177
SibSp,0
Parch,0
Ticket,0
Fare,0


In [24]:
data.groupby("Sex")["Survived"].mean() * 100

,Survived
Sex,
female,74.203822
male,18.890815


In [25]:
data["Age"].mean()

np.float64(29.69911764705882)

In [26]:
data["Age"].median()

28.0

In [27]:
data["Age"].std()

14.526497332334044

In [28]:
data["Pclass"].value_counts()

,count
Pclass,
3,491
1,216
2,184


In [41]:
female_child_survived = data[
    (data["Sex"] == "female") &
    (data["Age"] < 18) &
    (data["Survived"] == 1)
]

female_child_survived


,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,330923,8.0292,NaN,Q
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,2651,11.2417,NaN,C
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
58,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,NaN,S
68,69,1,3,"Andersson, Miss. Erna Alexandra",female,17.00,4,2,3101281,7.9250,NaN,S
84,85,1,2,"Ilett, Miss. Bertha",female,17.00,0,0,SO/C 14885,10.5000,NaN,S
156,157,1,3,"Gilnagh, Miss. Katherine ""Katie""",female,16.00,0,0,35851,7.7333,NaN,Q
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,NaN,S


In [43]:
median_age = data["Age"].median()
data["Age"].fillna(median_age)


,Age
0,22.0
1,38.0
2,26.0
3,35.0
4,35.0
...,...
886,27.0
887,19.0
888,28.0
889,26.0


In [44]:
def age_category(age):
    if age < 18:
        return "Child"
    elif age <= 60:
        return "Adult"
    else:
        return "Senior"

data["age_group"] = data["Age"].apply(age_category)

data[["Age", "age_group"]].head(10)

,Age,age_group
0,22.0,Adult
1,38.0,Adult
2,26.0,Adult
3,35.0,Adult
4,35.0,Adult
5,NaN,Senior
6,54.0,Adult
7,2.0,Child
8,27.0,Adult
9,14.0,Child


In [45]:
data.sort_values(by="Fare", ascending=False).head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,age_group
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,Adult
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,Adult
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,Adult
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S,Adult
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S,Senior


In [46]:
data.groupby(["Pclass", "Sex"])["Fare"].mean()

Pclass  Sex   
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: Fare, dtype: float64

In [62]:
data.rename(
    columns={"Sex": "gender","Fare": "ticket_fare"},
    inplace = True
)
data

,PassengerId,Survived,Pclass,Name,gender,Age,SibSp,Parch,Ticket,ticket_fare,Cabin,Embarked,age_group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Adult
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Senior
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Adult


In [52]:
data.groupby(["Pclass", "Survived"]).size().unstack()
# 0 means not survived, 1 means survived ; .unstack is not necessary

Survived,0,1
Pclass,,
1,80,136
2,97,87
3,372,119


In [63]:
data.groupby(["Pclass", "gender"])["Age"].mean()

Pclass  gender
1       female    34.611765
        male      41.281386
2       female    28.722973
        male      30.740707
3       female    21.750000
        male      26.507589
Name: Age, dtype: float64